baseURL                   = "https://alimorpeth.com"
builddrafts                = false
languageCode               = "en-uk"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "docs"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Ali Morpeth"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"

#[menu]

#  [[menu.main]]
#    name                   = "About"
#    weight                 = -110
#    identifier             = "about"
#    url                    = "#about"






[params]
  faviconfile              = "img/favicon.png"               # from static/
  avatar                   = "img/ali-morpeth.jpg"             # path to image in static dir e.g img/avatar.png
  author                   = "Ali Morpeth"
  description              = ["Nutrition Coach", " Working with families", "to support their health goals"]           # appears in the site header when set to a non-empty string
#  welcome_head             = "Hello, World!"
#  welcome_word             = "~ No Day But Today ~"

  # latestpostscount         = 5                             # how many posts to display on the home page
  # bloggroupby              = 'month'
  # dateform                 = "Jan 2, 2006"
  # dateformfull             = "2006-01-02  Monday  15:04:05"
  # noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "hello@alimorpeth.com"
  # github                   = "//github.com/you"
  linkedin                 = "//linkedin.com/in/alimorpeth"
  facebook                 = "//facebook.com/alimopethnutrition"
  #googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/alimorpeth"
  #px500                    = "//px500"
  instagram                = "//instagram.com/rumplecroft_eats"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon

  # analytics
  googleAnalytics          = "your-google-analytic-id"
